# Generated by Django 5.0.6 on 2024-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
        migrations.AddField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(related_name="projects", to="portfolio.link"),
        ),
    ]
