# Generated by Django 5.0.6 on 2024-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_technologies_project_technologies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Technologies",
        ),
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="portfolio.technology"
            ),
        ),
    ]
